package goqueue

import (
	"encoding/json"
	"time"
)

// Job represents a single queue entry returned by Claim.
type Job struct {
	ID             int64
	QueueName      string
	IdempotencyKey *string
	Payload        json.RawMessage
	State          string
	Priority       int
	Attempts       int
	MaxAttempts    int
	NextAttemptAt  time.Time
	ClaimedBy      *string
	// ClaimedAt is set when the job is claimed.
	// Note: claim timestamps are generated by MySQL using NOW(), so comparing them
	// to time.Now() is subject to Go/MySQL clock skew.
	ClaimedAt *time.Time
	// ClaimedUntil is the lease deadline. When returned from Claim(), this is
	// generated by MySQL (NOW() + INTERVAL ...). Comparing it to time.Now() is
	// subject to Go/MySQL clock skew. Use a safety margin when scheduling lease
	// extensions (e.g. extend well before this timestamp).
	ClaimedUntil *time.Time
	LastError      *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    *time.Time
}
